import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Nav from "@/components/Nav";
import Cart from "@/components/Cart";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "myStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <div className="flex min-h-screen font-montserrat w-full">
          <Nav />
          <Toaster position="top-center" />
          <main className={`flex-grow pt-2 md:pt-16 w-full`}>
          {children}
          <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
