import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import Head from "next/head";
import LayoutWrapper from "@/components/LayoutWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
